### ISSUE TITLE
Sounds für auditives Feedback finden

### ISSUE THREAD

**Issue by ataulien** [ataulien/MottSt#11]
Sounds für folgende Aktionen, soweit möglich:
 * Gast ruft genervt (steht in der Schlage)
 * Gast ruft genervt (will bestellen)
 * Gast ruft genervt (will essen)
 * Gast ruft genervt (will zahlen)
 * Tellerklappern (Hinstellen)
 * Tellerklappern (Aufsammeln)
 * Bestellung aufgenommen ("Kommt sofort", etc)
 * Bestellung abgeben (Papierrascheln)
 * Hintergrundgedudel

**Comment by ataulien** [comment]
Außerdem brauchen wir natürlich eine Möglichkeit die Sounds abzuspielen!

**Comment by fdohse** [comment]
Hintergrundmusik etwas leiser und die Signale der Kunden deutlicher
