### ISSUE TITLE
Status-Tabelle ersetzen

### ISSUE THREAD

**Issue by fdohse** [ataulien/MottSt#14]
Die Status-Tabelle soll komplett durch Signale der Gäste u.Ä. ersetzt werden

**Comment by beje8442** [comment]
Status tabelle ist entfernt, Kunden zeigen Zustände durch Grafiken an.
Kellner hat verschiedene Grafiken für Anzahl der Bestellungen und Tischnummern werden über dem Tablett abgebildet
