### ISSUE TITLE
Levelsystem implementieren

### ISSUE THREAD

**Issue by ataulien** [ataulien/MottSt#20]
Klasse, in der Eigenschaften der verschiedenen Level hinterlegt sind mit einfachen Interface zum Einstellen.

**Comment by beje8442** [comment]
- Level 1: 20 Gäste / 4 Tische

- Level 2:  30 Gäste / 5 Tische

- Level 3: 30 Gäste / 6 Tische / Sichtbarer Bereich wird kleiner

**Comment by fdohse** [comment]
Die Tische pro Level sind noch nicht korrekt eingestellt.. hier bitte nochmal anpassen (1. Level 4 Tische, 2. Level 5 Tische, 3. Level 6 Tische)

**Comment by ataulien** [comment]
Ist nun umgesetzt in 8ce4666.
