### ISSUE TITLE
Kaffeeautomat Funktionalität

### ISSUE THREAD

**Issue by fdohse** [ataulien/MottSt#26]
Wenn der Kellner Kaffee trinkt, dann wird der sichtbare Bereich kurz (10 Sekunden) größer.
Der Kellner braucht 3 Sekunden, um den Kaffee zu trinken (sollte angezeigt werden).

**Comment by matthiasgramm** [comment]
noch aktive Kaffeetasse im Füllstatus
3 Sek. Zeit
