### ISSUE TITLE
Eyetracking für Processing

### ISSUE THREAD

**Issue by ataulien** [ataulien/MottSt#3]
Es gibt eine DLL vom Eyetracker, für die ein Java-Interface gebraucht wird.

**Comment by ataulien** [comment]
Erste Version Commited, allerdings mangels  Windows-System noch ungetestet...

**Comment by fdohse** [comment]
@ataulien Hast du den EyeTracker schon besorgt? 
Wir müssten bis zum 28.05. das Spiel mit Eyetracking getestet haben..

**Comment by fdohse** [comment]
Eventuell testen wir bis zum 28.05 im Versatel-Gebäude die Eyetracking-Funktionalität

**Comment by ataulien** [comment]
@fdohse Leider waren letzte Woche alle Eyetracker reserviert, und dass auch diese und/oder nächste Woche. Am besten nochmal bei Sascha nachfragen, wann wieder einer zu bekommen ist.

**Comment by ataulien** [comment]
Anbindung an den Eyetracker funktioniert. Kalibrierung ist auch drin.
